steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'
  - task: Cache@2
    displayName: Cache Yarn packages
    inputs:
      key: 'yarn.lock'
      path: '$(System.DefaultWorkingDirectory)/node_modules'
      cacheHitVar: CacheRestored
  - script: |
      yarn install --ignore-engines --frozen-lockfile
    displayName: Install dependencies only if there is no cache available
    # condition: ne(variables['CacheRestored'], 'true')
